# Gemini Code Assistant レビュー設定

## レビュー言語
- レビュー言語: 日本語
- コードコメント: 英語

## レビュー基準とプレフィックス

### [must] - 重大な問題（修正必須）
- セキュリティ脆弱性: 認証・認可の欠陥、SQLインジェクション、XSS等
- 重大なバグ: データ損失、クラッシュの原因
- アーキテクチャ違反: ADRで決定した設計原則からの逸脱
- テスト不足: カバレッジ80%未満、重要なパスのテスト欠如

### [should] - 推奨される改善
- コード品質: 可読性、保守性の問題
- パフォーマンス: 明らかな非効率さ
- エラーハンドリング: 不十分な例外処理
- 型安全性: 不適切な型使用

### [question] - 確認事項
- 設計判断: 実装の意図、代替案の検討
- 仕様確認: 要件との整合性
- エッジケース: 考慮漏れの可能性

### [nits] - 小さな改善点（Nitpicks）
- 命名規則: 変数名、関数名の改善
- コメント: 不要なコメント、不足しているドキュメント
- コードスタイル: 整形、空白の一貫性
- 重複: 重複コードの抽出機会

### [nr] - 返信不要（No Response Needed）
- 単純な承認
- 良い実装の賞賛

## プロジェクト特有の基準

### アーキテクチャ（ADR-005: 3層アーキテクチャ）
- [must] Controller -> Service -> Repository のレイヤ分離を守る
- [must] ドメインモデルはイミュータブル
- [should] サービス層でビジネスロジックを集約
- [should] Repositoryはインターフェースと実装を分離

### バックエンド（Kotlin/Spring Boot）
- [must] トランザクション境界を適切に設定
- [must] バリデーションをAPI境界で実施
- [should] 例外処理はGlobalExceptionHandlerで集約
- [nits] Kotlinイディオムの活用（data class, 拡張関数等）

### フロントエンド（Next.js/React）
- [must] APIエラー時の適切なUX（エラーメッセージ表示）
- [should] ローディング状態の表示
- [should] レスポンシブデザイン
- [nits] TypeScriptの型定義の明確化

### テスト
- [must] TDDサイクルの遵守（Red -> Green -> Refactor）
- [must] カバレッジ80%以上
- [should] テストの可読性（ arrange-act-assertパターン）
- [nits] テスト名の説明的命名

### Git/コミット
- [should] Conventional Commits準拠（feat, fix, refactor等）
- [nits] コミットメッセージの具体性
- [nr] 日本語でのコミットメッセージ

## 回答フォーマット例

```markdown
## [must] SQLインジェクションの脆弱性
`UserRepository.kt:45`でクエリ文字列の結合を行っています...
修正案: パラメータ化クエリを使用...

## [question] キャッシュ戦略について
このエンドポイントは頻繁にアクセスされますが...
キャッシュの導入を検討しましたか？

## [nits] 変数名の改善
`x` -> `userCount` の方が可読性が高くなります

## [nr] 良い実装です
TDDでテストファーストで書かれており、カバレッジも十分です
```

## 無視するファイル
- `node_modules/`
- `.next/`
- `build/`
- `dist/`
- `*.min.js`
- `package-lock.json`
- `pnpm-lock.yaml`
- `.git/`
